version: '3.8'
services:
  postgres:
    container_name: postgres-docker-container
    restart: always
    build: ./postgres-docker
    volumes:
      - /var/lib/postgres-docker
    ports:
      - '5433:5432'
    #environment:
    #  - ./.env

  node-docker:
    container_name: node-docker-container
    restart: always
    build:
      context: ./node-docker
      target: dev
    volumes:
      - ./node-docker:/src
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@node-docker-container:5432/testdb
      NODE_ENV: dev
    depends_on:
      - postgres

  angular-docker:
    container_name: angular-docker-container
    build: ./angular-docker
    ports:
      - '9000:80'
    depends_on:
      - postgres

  flask-docker:
    container_name: flask-docker-container
    build: ./flask-docker
    ports:
      - '5000:5000'
    depends_on:
      - postgres
#volumes: db-data
#use named volumes
