version: '3.3'
services:
  postgres:
    container_name: postgres-docker-container
    restart: always
    build: ./postgres-docker
    volumes:
      - /var/lib/postgres-docker
    ports:
      - "5432:5432"
  
  node-docker:
    container_name: node-docker-container
    restart: always
    build: ./node-docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  angular-docker:
    container_name: angular-docker-container
    build: ./angular-docker
    ports:
      - '9000:80'
    depends_on:
      - postgres

  
